menuapp/urls.py
from django.urls import path
from .views import *

app_name = "menuapp"

urlpatterns = [

    # Client Page Urls Start
    path("", ClientHomeView.as_view(), name="clienthome"),
    path("gallery/", ClientGalleryView.as_view(), name="clientgallery"),
    path("service/", ClientServiceView.as_view(), name="clientservice"),

    path("enquery/", ClientEnqueryView.as_view(), name="clientenquery"),

    path("ajax/menu/", 
        AjaxGetItemsView.as_view(), name = "ajaxgetitems"),




    path("feedback/", ClientFeedbackView.as_view(), name="clientfeedback"),
    path("item-all/", ClientItemView.as_view(), name="clientitem"),
    # path("sidebar/", ClientSidebarView.as_view(), name="clientsidebar"),
	
	path("menu/<int:pk>/detail/", ClientMenuDetailView.as_view(), name= "clientmenudetail"),
	path("menu/specialitem/list/", 
		ClientSpecialItemListView.as_view(), name = "clientspecialitemlist"),


    path("search/", SearchView.as_view(), name = "search"),

    path("subscriber/", SubscriberCreateView.as_view(), name="clientsubscriber"),


    path('album/', ClientAlbumView.as_view(), name='clientalbum'),
    path("album/<int:pk>/detail", ClientAlbumDetailView.as_view(),name="clientalbumdetail"),


    path("add-to-basket/<int:pk>/", AddToBasketView.as_view(), name = "addtobasket"),

    path("basket/", BasketView.as_view(), name = 'basket'),
    path("order/", OrderCreateView.as_view(), name = "ordercreate"),
    path("order/list/", OrderListView.as_view(), name = 'orderlist'),
    path("order/<int:pk>/detail/", OrderDetailView.as_view(), name = 'orderdetail'),


    path("manage-basket/<int:pk>/<action>/", 
        ManageBasketView.as_view(), name = 'managebasket'),

    path("empty-basket/", 
        EmptyBasketView.as_view(), name = 'emptybasket'),

    path("customer/sign-up/", CustomerSignupView.as_view(), name = 'customersignup'),
    path("customer/login/", CustomerLoginView.as_view(), name = 'customerlogin'),







#--------------
#--------------
#--------------
#--------------
#--------------
#--------------

#----------------------
#----------------------
#----------------------
#----------------------
#----------------------


	# Admin Signin Form
	path("emenu-admin/signin/", AdminSigninView.as_view(), name = "adminsignin"),
	path("emenu-admin/signout/", AdminSignoutView.as_view(), name = "adminsignout"),
    # path("emenu-admin/signup/", AdminSignupView.as_view(), name = "adminsignup"),


# Admin Home View
    path("emenu-admin/home/", AdminHomeView.as_view(), name="adminhome"),

# Admin Banner Views
    path("emenu-admin/banner/list/", AdminBannerListView.as_view(), name="adminbannerlist"),
    path("emenu-admin/banner/create/", AdminBannerCreateView.as_view(), name="adminbannercreate"),
    path("emenu-admin/banner/<int:pk>/update/", AdminBannerUpdateView.as_view(), name="adminbannerupdate"),
    path("emenu-admin/banner/<int:pk>/delete/", AdminBannerDeleteView.as_view(), name="adminbannerdelete"),

# Admin Menu Views
    path("emenu-admin/menu/list/", AdminMenuListView.as_view(), name="adminmenulist"),
    path("emenu-admin/menu/create/", AdminMenuCreateView.as_view(), name="adminmenucreate"),
    path("emenu-admin/menu/<int:pk>/update/", AdminMenuUpdateView.as_view(), name="adminmenuupdate"),
    path("emenu-admin/menu/<int:pk>/delete/", AdminMenuDeleteView.as_view(), name="adminmenudelete"),

# Admin Menu Category Views
    path("emenu-admin/menu/<int:pk>/list/", AdminMenuDetailView.as_view(), name="adminmenudetail"),

# Admin All Items List View
    path("emenu-admin/items/list/", AdminItemListView.as_view(), name="adminitemlist"),
    path("emenu-admin/items/create/", AdminItemCreateView.as_view(), name="adminitemcreate"),
    path("emenu-admin/items/<int:pk>/update/", AdminItemUpdateView.as_view(), name="adminitemupdate"),
    path("emenu-admin/items/<int:pk>/delete/", AdminItemDeleteView.as_view(), name="adminitemdelete"),

# Admin All Special Items List View
    path("emenu-admin/specialitems/list/", AdminSpecialItemListView.as_view(), name="adminspecialitemlist"),
    path("emenu-admin/specialitems/create/", AdminSpecialItemCreateView.as_view(), name="adminspecialitemcreate"),
    path("emenu-admin/specialitems/<int:pk>/update/", 
        AdminSpecialItemUpdateView.as_view(), name="adminspecialitemupdate"),
    path("emenu-admin/specialitems/<int:pk>/delete/", 
        AdminSpecialItemDeleteView.as_view(), name="adminspecialitemdelete"),


# Admin Staff Urls
    path("emenu-admin/staff/list/", AdminStaffListView.as_view(), name="adminstafflist"),
    path("emenu-admin/staff/create/", AdminStaffCreateView.as_view(), name="adminstaffcreate"),
    path("emenu-admin/staff/<int:pk>/update/", 
        AdminStaffUpdateView.as_view(), name="adminstaffupdate"),
    path("emenu-admin/staff/<int:pk>/delete/", 
        AdminStaffDeleteView.as_view(), name="adminstaffdelete"),

    path("emenu-admin/about/", AdminAboutView.as_view(), name="adminabout"),
    path("emenu-admin/gallery/", AdminGalleryView.as_view(), name="admingallery"),


    path("emenu-admin/basket/list/", AdminBasketListView.as_view(), name = 'adminbasketlist'),








########### Sericalizers for making api
    path("json_api/staff/list-create/", StaffApiView.as_view(), name = 'staffapi'),
]

menuproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('emenu/django-admin/', admin.site.urls),
    path('', include("menuapp.urls")),

]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
#fetching static files to html files
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/clienttemplates/ajaxgetitems.html
{% for items in relateditems %}
<option value="{{items.id}}">{{items.name}} </option>

{% endfor %}

templates/clienttemplates/clientabout.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}


{% block title %}
C-About page
{% endblock %}

{% block about %}active{% endblock %}
{% block content %}


<!-- main content start-->
    <div id="page-wrapper">
        <!-- inner banner -->
        <div class="inner-banner">
        </div>
        <!-- //inner banner -->
        <!-- breadcrumbs -->
        <div class="inner-bc">
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'menuapp:clienthome' %}">Home</a>
                        </li>
                        <li class="breadcrumb-item active  text-capitalize" aria-current="page">About Us</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- //breadcrumbs -->
        <!-- stats -->
        <section class="agile_stats">
            <div class="container-fluid pt-5">
                <div class="row pt-lg-5 w3-abbottom">
                    <div class="col-lg-6 px-sm-5 px-3">
                        {% for rest in restro %}
                        <div class="stats_agile mb-5">
                            <h3 class="stat-title text-uppercase">{{ rest.name }}</h3>
                            <span class="w3-line"></span>
                            <p class="mt-3">{{ rest.about }}</p>
                        </div>

                        <div class="row">
                            <div class="counter col-4">
                                <i class="far fa-smile fa-2x"></i>
                                <div class="timer count-title count-number mt-2" data-to="1000" data-speed="1500"></div>
                                <p class="count-text text-capitalize">Happy Customers</p>
                            </div>

                            <div class="counter col-4 px-4">
                                <i class="fas fa-database fa-2x"></i>
                                <div class="timer count-title count-number mt-2" data-to="100" data-speed="1500"></div>
                                <p class="count-text text-capitalize">Items</p>
                            </div>

                            <div class="counter col-4">
                                <i class="fab fa-slideshare fa-2x"></i>
                                <div class="timer count-title count-number mt-2" data-to="200" data-speed="1500"></div>
                                <p class="count-text text-capitalize">Specials Served</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <img src="{{ rest.profile_image.url }}" class="img-fluid" alt="" />
                    </div>
                    {% endfor %}

                </div>
            </div>
        </section>
        <!-- //stats -->
       

        <section class="wthree-row pt-md-5 pt-0">
            <div class="py-sm-5 pt-3 pb-4 bg-pricemain text-center">
                <h3 class="agile-title text-uppercase">Our Valuable Staffs</h3>
                <span class="w3-line"></span>
            </div>
            <div class="row justify-content-center align-items-center no-gutters abbot-main">
                <div class="row">
                    {% for staff in allstaffs %}
                    <div class="col-md-4">
                    <h4>
                    {{ staff.name }}
                    </h4>
                    <img src="{{ staff.photo.url }}" width = 150>
                    <h4>
                    Position: {{ staff.position }}
                    </h4>
                    <h4>
                    Experience: {{staff.experience}} years
                    </h4>
                    <hr>
                    </div>
                    {% endfor %}
                        
                </div>
            </div>
        </section>


{% endblock %}

templates/clienttemplates/clientaddtobasket.html
<h3>Product added to your Basket successfully.</h3>

templates/clienttemplates/clientfeedback.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}


{% block title %}
C-Feedback page
{% endblock %}

{% block feedback %}active{% endblock %}
{% block content %}


 <!-- main content start-->
    <div id="page-wrapper">
        <!-- inner banner -->
        <div class="inner-banner">
        </div>
        <!-- //inner banner -->
        <!-- breadcrumbs -->
        <div class="inner-bc">
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'menuapp:clienthome' %}">Home</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Feedback</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- //breadcrumbs -->

        <!-- contact -->
        <section class="wthree-row pt-3 pb-5 w3-contact">
            <div class="container py-sm-5 pt-0 pb-5">
                <div class="py-lg-5 bg-pricemain text-center">
                    <h3 class="agile-title text-uppercase">Feedback</h3>
                    <span class="w3-line"></span>
                </div>

            <div class="row">
                {% for feed in allfeeds|slice:"4" %}
                    <div class="col-md-3">
                    <div class="card-body bg-success text-center">
                    <h5 class="card-title ">Name: {{ feed.name }}</h5>
                    <p class="card-text mb-3 ">Message: {{ feed.message }}</p>
                    </div>
                    </div>
                {% endfor %}
            </div>




                <div class="row contact-form pt-5">
                    <div class="col-lg-6 wthree-form-left">
                        <!-- contact form grid -->
                        <div class="contact-top1">
                            <h5 class="text-dark mb-4 text-capitalize">Send us your feedback</h5>
                            <form action="." method="post" class="f-color">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="contactusername">Name</label>
                                    {{ form.name }}
                                </div>
                                <div class="form-group">
                                    <label for="contactemail">Email</label>
                                    {{ form.email }}
                                </div>
                                <div class="form-group">
                                    <label for="contactcomment">Your Message</label>
                                    {{ form.message }}
                                </div>
                                <button type="submit" class="btn btn-info btn-block">Submit</button>
                            </form>
                        </div>
                        <!--  //contact form grid ends here -->
                    </div>
                    <!-- contact details -->
                    {% for rest in restro %}
                    <div class="col-lg-6 contact-bottom pl-5 mt-lg-0 mt-5">
                        <h4>Our Contact Information</h4><hr>
                        <!-- contact details grid1-->
                        <div class="address">
                            <h5 class="pb-3 text-capitalize">Address</h5>
                            <address>
                                <p class="c-txt">{{ rest.address }}</p>
                            </address>
                        </div>
                        <!-- contact details grid2-->
                        <div class="address my-5">
                            <h5 class="pb-3 text-capitalize">phone</h5>
                            <p>
                                {{ rest.phone }}</p>
                            <p>
                                {{ rest.mobile }}</p>
                        </div>
                        <!-- contact details grid3 -->
                        <div class="address mt-md-0 mt-3">
                            <h5 class="pb-3 text-capitalize">Email</h5>
                            <p>
                                <a href="mailto:info@example.com">{{ rest.email }}</a>
                            </p>
                            <p>
                                <a href="mailto:info@example.com">{{ rest.website }}</a>
                            </p>
                        </div>
                        <!-- //contact details row ends here -->
                    </div>
                    {% endfor %}
                </div>
                <!-- //contact details container -->
            </div>
            <!-- contact map grid -->
            <div class="map contact-right p-sm-5 px-3">
                <div class="py-5 bg-pricemain text-center">
                    <h3 class="stat-title text-capitalize">get directions</h3>
                    <span class="w3-line"></span>
                </div>
               <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3533.99222256216!2d85.31953941453719!3d27.655712334367262!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb177ecff27973%3A0xb57b2fbfc94f7fe7!2sSarobar+Technology+Pvt.+Ltd.!5e0!3m2!1sen!2snp!4v1564589062937!5m2!1sen!2snp" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
            <!--//contact map grid ends here-->
        </section>





{% endblock %}

templates/clienttemplates/clienthome.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}


{% block title %}
C-HomePage
{% endblock %}


{% block home %}active{% endblock %}

{% block content %}


<!-- main content start-->
	<div id="page-wrapper">
		<div class="banner">
			<div class="banner_text_agile">
				<!-- Carousel -->
				<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
					<ol class="carousel-indicators">
						<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
						<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
						<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
					</ol>
					<div class="carousel-inner">
						{% for slider in allsliders %}
						<div class="carousel-item {% if forloop.counter == 1 %}active{% endif %} text-center">
							<i class="fab fa-connectdevelop"></i>
							<h3 class="b-w3ltxt text-capitalize mt-4">{{slider.title}}</h3>
							<p class="mx-auto text-capitalize mt-2">{{slider.caption}}</p>
							<a class="btn btn-banner mt-md-3 mt-2 text-capitalize" href="{% url 'menuapp:clientspecialitemlist' %}" role="button">{{slider.link}}</a>
						</div>
						{% endfor %}
						<!-- slider text -->
					</div>
				</div>
				<!-- Carousel -->
			</div>


		</div>
		<!-- //banner -->



            

 <!-- stats -->
        <section class="agile_stats">
            <div class="container-fluid pt-5">
                <div class="row pt-lg-5 w3-abbottom">
                    <div class="col-lg-6 px-sm-5 px-3">
                        {% for rest in restro %}
                        <div class="stats_agile mb-5">
                            <h3 class="stat-title text-uppercase">{{ rest.name }}</h3>
                            <span class="w3-line"></span>
                            <p class="mt-3">{{ rest.about }}</p>
                        </div>

                        <div class="row">
                            <div class="counter col-4">
                                <i class="far fa-smile fa-2x"></i>
                                <div class="timer count-title count-number mt-2" data-to="1000" data-speed="1500"></div>
                                <p class="count-text text-capitalize">Happy Customers</p>
                            </div>

                            <div class="counter col-4 px-4">
                                <i class="fas fa-database fa-2x"></i>
                                <div class="timer count-title count-number mt-2" data-to="100" data-speed="1500"></div>
                                <p class="count-text text-capitalize">Items</p>
                            </div>

                            <div class="counter col-4">
                                <i class="fab fa-slideshare fa-2x"></i>
                                <div class="timer count-title count-number mt-2" data-to="200" data-speed="1500"></div>
                                <p class="count-text text-capitalize">Specials Served</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <img src="{{ rest.profile_image.url }}" class="img-fluid" alt="" />
                    </div>
                    {% endfor %}

                </div>
            </div>
        </section>
        <!-- //stats -->

        <div class="py-lg-5 py-3 bg-pricemain text-center">
                    <h3 class="agile-title text-uppercase">Our Menu Album</h3>
                    <span class="w3-line"></span>
                </div>
            <div class="row">
				{% for album in allalbum %}
					<div class="col-md-3">
    					<img class="card-img-top" src="{{ album.profile_image.url }}" width="250" height="200">
    					<div class="card-body bg-light text-center">
    					<h5 class="card-title ">{{ album.title }}</h5>
    					<a href="{% url 'menuapp:clientalbumdetail' album.id %}" class="btn">View More</a>
    					</div>
					</div>
				{% endfor %}
            </div>
       

        <section class="wthree-row pt-md-5 pt-0">
            <div class="py-sm-5 pt-3 pb-4 bg-pricemain text-center">
                <h3 class="agile-title text-uppercase">Our Valuable Staffs</h3>
                <span class="w3-line"></span>
            </div>
            <div class="row justify-content-center align-items-center no-gutters abbot-main">
                <div class="row">
                    {% for staff in allstaffs %}
                    <div class="col-md-4">
                    <h4>
                    {{ staff.name }}
                    </h4>
                    <img src="{{ staff.photo.url }}" width = 150>
                    <h4>
                    Position: {{ staff.position }}
                    </h4>
                    <h4>
                    Experience: {{staff.experience}} years
                    </h4>
                    <hr>
                    </div>
                    {% endfor %}
                        
                </div>
            </div>
        </section>

{% endblock %}

templates/clienttemplates/clientitem.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}


{% block title %}
C-Menu Item Page
{% endblock %}

{% block item %}active{% endblock %}
{% block content %}



<!-- main content start-->
    <div id="page-wrapper">
        <!-- inner banner -->
        <div class="inner-banner">
        </div>
        <!-- //inner banner -->
        <!-- breadcrumbs -->
        <div class="inner-bc">
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'menuapp:clienthome' %}">Home</a>
                        </li>
                        <li class="breadcrumb-item active  text-capitalize" aria-current="page">All Items</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- //breadcrumbs -->

         
                <div class="py-lg-5 py-3 bg-pricemain text-center">
                    <h3 class="agile-title text-uppercase">Today's Menu Items</h3>
                    <span class="w3-line"></span>
                </div>
            <div class="row">
				{% for items in allitems %}
					<div class="col-md-3">
    					<img class="card-img-top" src="{{ items.photo.url }}" width="250" height="200">
    					<div class="card-body bg-light text-center">
    					<h5 class="card-title ">{{ items.name }}</h5>
    					<p class="card-text mb-3 ">Price: Rs.{{ items.price }}/-</p>
    					<button type="btn" class="add-to-basket" data-href="{% url 'menuapp:addtobasket' items.id %}">Order Now</button>
    					</div>
					</div>
				{% endfor %}
            </div>

{% if allitems.has_other_pages %}
<ul class="pagination">
    {% if allitems.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ allitems.previous_page_number }}">Previous</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
    {% endif %}
    {% for n in allitems.paginator.page_range %}
        {% if allitems.number == n %}
            <li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{n}}</a></li>
        {% endif %}
    {% endfor %}
    {% if allitems.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ allitems.next_page_number}}">Next</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">Next</span></li>
    {% endif %}
</ul>
{% endif %}
          



           <!--  <div class="row">
            	<div class="col-md-3">
                    {% for items in allitems %}
                    <h4>{{ items.name }}</h4>
                    <img src="{{ items.photo.url }}" width="250">
                    <h5>{{ items.price }}</h5>
                    {% endfor %}
                </div>
            </div> -->
							                     


{% endblock %}

templates/clienttemplates/clientmanagebasket.html
<h4>
	{{message}}
</h4>

templates/clienttemplates/customerlogin.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
	Ecom-Customer Login Page		
	</title>
</head>
<body class="container-fluid">

<div class="row">
	<div class="col-md-6 mx-auto">
		<h4>Customer Signin Form</h4><hr>
		<form method="post">
			{% if error %}
			<li class="text-danger">{{error}}</li>
			{% endif %}
			{% csrf_token %}
			{{form.as_p}}
			<input type="submit" name="Login" class="btn btn-info">		
		</form>	
	</div>
</div>





</body>
</html>

templates/clienttemplates/orderlist.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
Orders List
{% endblock %}

{% block your_order %}active{% endblock %}

{% block content %}


<!-- main content start-->
    <div id="page-wrapper">
        <!-- inner banner -->
        <div class="inner-banner">
        </div>
        <!-- //inner banner -->
        <!-- breadcrumbs -->
        <div class="inner-bc">
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'menuapp:clienthome' %}">Home</a>
                        </li>
                        <li class="breadcrumb-item active  text-capitalize" aria-current="page">My Orders</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- //breadcrumbs -->

        <div class="py-lg-5 py-3 bg-pricemain text-center">
			{% if request.user.is_authenticated %}
			<h3 class="agile-title text-uppercase" align="text-left">Order List of '{{request.user}}' Customer</h3>
			{% else %}
			<h3 class="agile-title text-uppercase">Sorry, You must be logged in first to see orders.</h3>
			{% endif %}
            <span class="w3-line"></span>
        </div>
        <p id="myp"></p>
       	<div id="my-content">
			<table class="table" id="my-table">
				<thead>
					<tr>
						<th>SN</th>
						<th>Order ID</th>
						<th>Order By</th>
						<th>Order Total</th>
						<th>Order Status</th>
						<th>Payment Method</th>
					</tr>
				</thead>
				<tbody>
					{% for order in allorders %}
					<tr class='clickable-row' data-href="{% url 'menuapp:orderdetail' order.id %}">
						<td>{{forloop.counter}}</td>
						<td>ID: '{{order.id}}'</td>
						<td>{{order.customer}}</td>
						<td>{{order.total}}</td>
						<td>{{order.order_status}}</td>
						<td>{{order.payment_method}}</td>
					</tr>
					{% endfor %}
				</tbody>
				
			</table>
		</div>

{% endblock %}


{% block js %}

	<script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".clickable-row").click(function() {
				window.location = $(this).attr("data-href");
			});
		});
	</script>





<!-- <script type="text/javascript">
	$(document).ready(function(){
		$(".basket-manage").on("click", function(){
			$("#my-content").on("click", ".basket-manage", function(){
			var url_end_point = $(this).attr("href");
			$.ajax({
				method: 'get',
				url: url_end_point,
				data: {

				},
				success: function(data){
					$("#my-content").load("#my-content #my-table");
					$('#myp').html(data).css("display", 'block');
					setTimeout(fade_out, 3000);
						function fade_out() {
					$("#myp").fadeOut().empty();
					}
				}
			})
		  })
		})
	})
</script>

	<script>
	    $(document).ready(function(){ 
	        $("#empty-basket").on("click", function(){
				var empty_url = $(this).attr("href");
				$.ajax({
					method: 'get',
					url: empty_url,
					data: {

					},
					success: function(data){
						$("#my-content").load("#my-content #my-table");
						$('#myp').html(data).css("display", 'block');
						setTimeout(fade_out, 5000);
							function fade_out() {
						$("#myp").fadeOut().empty();
						}
					}
				});
			});
		});
	</script> -->
{% endblock %}

templates/clienttemplates/search.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
search
{% endblock %}



{% block content %}

<!-- main content start-->
    <div id="page-wrapper">
        <!-- inner banner -->
        <div class="inner-banner">
        </div>
        <!-- //inner banner -->
        <!-- breadcrumbs -->
        <div class="inner-bc">
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'menuapp:clienthome' %}">Home</a>
                        </li>
                        <li class="breadcrumb-item active  text-capitalize" aria-current="page">Search Result: "{{request.GET.alias}}"</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- //breadcrumbs -->



			<div class="row">
			{% for search in allitems %}
				<div class="col-md-3">
					<img class="card-img-top" src="{{ search.photo.url }}" width="250" height="200">
					<div class="card-body bg-light text-center">
					<h5 class="card-title ">{{ search.name }}</h5>
					<p class="card-text mb-3 ">Price: Rs.{{ search.price }}/-</p>
					<button type="btn" class="add-to-basket" data-href="{% url 'menuapp:addtobasket' items.id %}">Order Now</button>
					</div>
				</div>
				<hr>
				{% empty %}
				<div class="col-md-3">
					<p class="card-text mb-3 ">No results found</p>
				</div>
			{% endfor %}
			</div>

			{% if allitems.has_other_pages %}
			<ul class="pagination">
				{% if allitems.has_previous %}
				<li class="page-item"><a class="page-link" href="?page={{ allitems.previous_page_number }}&alias={{request.GET.alias}}">Previous</a></li>
				{% else %}
				<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
				{% endif %}
				{% for n in allitems.paginator.page_range %}
					{% if allitems.number == n %}
						<li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
					{% else %}
						<li class="page-item"><a class="page-link" href="?page={{ n }}&alias={{request.GET.alias}}">{{n}}</a></li>
					{% endif %}
				{% endfor %}
				{% if allitems.has_next %}
			      <li class="page-item"><a class="page-link" href="?page={{ allitems.next_page_number}}&alias={{request.GET.alias}}">Next</a></li>
			    {% else %}
			      <li class="page-item disabled"><span class="page-link">Next</span></li>
			    {% endif %}
			</ul>
			{% endif %}

{% endblock %}