menuapp/urls.py
from django.urls import path
from .views import *

app_name = "menuapp"

urlpatterns = [

    # Client Page Urls Start
    path("", ClientHomeView.as_view(), name="clienthome"),
    path("gallery/", ClientGalleryView.as_view(), name="clientgallery"),
    path("service/", ClientServiceView.as_view(), name="clientservice"),

    path("enquery/", ClientEnqueryView.as_view(), name="clientenquery"),

    path("ajax/menu/", 
        AjaxGetItemsView.as_view(), name = "ajaxgetitems"),




    path("feedback/", ClientFeedbackView.as_view(), name="clientfeedback"),
    path("item-all/", ClientItemView.as_view(), name="clientitem"),
    # path("sidebar/", ClientSidebarView.as_view(), name="clientsidebar"),
	
	path("menu/<int:pk>/detail/", ClientMenuDetailView.as_view(), name= "clientmenudetail"),
	path("menu/specialitem/list/", 
		ClientSpecialItemListView.as_view(), name = "clientspecialitemlist"),


    path("search/", SearchView.as_view(), name = "search"),

    path("subscriber/", SubscriberCreateView.as_view(), name="clientsubscriber"),


    path('album/', ClientAlbumView.as_view(), name='clientalbum'),
    path("album/<int:pk>/detail", ClientAlbumDetailView.as_view(),name="clientalbumdetail"),


    path("add-to-basket/<int:pk>/", AddToBasketView.as_view(), name = "addtobasket"),

    path("basket/", BasketView.as_view(), name = 'basket'),
    path("order/", OrderCreateView.as_view(), name = "ordercreate"),
    path("order/list/", OrderListView.as_view(), name = 'orderlist'),
    path("order/<int:pk>/detail/", OrderDetailView.as_view(), name = 'orderdetail'),


    path("manage-basket/<int:pk>/<action>/", 
        ManageBasketView.as_view(), name = 'managebasket'),

    path("empty-basket/", 
        EmptyBasketView.as_view(), name = 'emptybasket'),

    path("customer/sign-up/", CustomerSignupView.as_view(), name = 'customersignup'),
    path("customer/login/", CustomerLoginView.as_view(), name = 'customerlogin'),







#--------------
#--------------
#--------------
#--------------
#--------------
#--------------

#----------------------
#----------------------
#----------------------
#----------------------
#----------------------


	# Admin Signin Form
	path("emenu-admin/signin/", AdminSigninView.as_view(), name = "adminsignin"),
	path("emenu-admin/signout/", AdminSignoutView.as_view(), name = "adminsignout"),
    # path("emenu-admin/signup/", AdminSignupView.as_view(), name = "adminsignup"),


# Admin Home View
    path("emenu-admin/home/", AdminHomeView.as_view(), name="adminhome"),

# Admin Banner Views
    path("emenu-admin/banner/list/", AdminBannerListView.as_view(), name="adminbannerlist"),
    path("emenu-admin/banner/create/", AdminBannerCreateView.as_view(), name="adminbannercreate"),
    path("emenu-admin/banner/<int:pk>/update/", AdminBannerUpdateView.as_view(), name="adminbannerupdate"),
    path("emenu-admin/banner/<int:pk>/delete/", AdminBannerDeleteView.as_view(), name="adminbannerdelete"),

# Admin Menu Views
    path("emenu-admin/menu/list/", AdminMenuListView.as_view(), name="adminmenulist"),
    path("emenu-admin/menu/create/", AdminMenuCreateView.as_view(), name="adminmenucreate"),
    path("emenu-admin/menu/<int:pk>/update/", AdminMenuUpdateView.as_view(), name="adminmenuupdate"),
    path("emenu-admin/menu/<int:pk>/delete/", AdminMenuDeleteView.as_view(), name="adminmenudelete"),

# Admin Menu Category Views
    path("emenu-admin/menu/<int:pk>/list/", AdminMenuDetailView.as_view(), name="adminmenudetail"),

# Admin All Items List View
    path("emenu-admin/items/list/", AdminItemListView.as_view(), name="adminitemlist"),
    path("emenu-admin/items/create/", AdminItemCreateView.as_view(), name="adminitemcreate"),
    path("emenu-admin/items/<int:pk>/update/", AdminItemUpdateView.as_view(), name="adminitemupdate"),
    path("emenu-admin/items/<int:pk>/delete/", AdminItemDeleteView.as_view(), name="adminitemdelete"),

# Admin All Special Items List View
    path("emenu-admin/specialitems/list/", AdminSpecialItemListView.as_view(), name="adminspecialitemlist"),
    path("emenu-admin/specialitems/create/", AdminSpecialItemCreateView.as_view(), name="adminspecialitemcreate"),
    path("emenu-admin/specialitems/<int:pk>/update/", 
        AdminSpecialItemUpdateView.as_view(), name="adminspecialitemupdate"),
    path("emenu-admin/specialitems/<int:pk>/delete/", 
        AdminSpecialItemDeleteView.as_view(), name="adminspecialitemdelete"),


# Admin Staff Urls
    path("emenu-admin/staff/list/", AdminStaffListView.as_view(), name="adminstafflist"),
    path("emenu-admin/staff/create/", AdminStaffCreateView.as_view(), name="adminstaffcreate"),
    path("emenu-admin/staff/<int:pk>/update/", 
        AdminStaffUpdateView.as_view(), name="adminstaffupdate"),
    path("emenu-admin/staff/<int:pk>/delete/", 
        AdminStaffDeleteView.as_view(), name="adminstaffdelete"),

    path("emenu-admin/about/", AdminAboutView.as_view(), name="adminabout"),
    path("emenu-admin/gallery/", AdminGalleryView.as_view(), name="admingallery"),


    path("emenu-admin/basket/list/", AdminBasketListView.as_view(), name = 'adminbasketlist'),








########### Sericalizers for making api
    path("json_api/staff/list-create/", StaffApiView.as_view(), name = 'staffapi'),
]

menuproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('emenu/django-admin/', admin.site.urls),
    path('', include("menuapp.urls")),

]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
#fetching static files to html files
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/admintemplates/adminbannerdelete.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Banner Delete Page
{% endblock %}



{% block content %}

<h3>Slide Banner Delete</h3>
<form method="POST">
	{% csrf_token %}
	<p>Are you sure you want to delete === " {{object.title}} " slide banner ????</p>
	<button class="btn btn-danger">Yes</button>
	<a href="{% url 'menuapp:adminbannerlist' %}" class="btn btn-primary">No</a>

</form>


{% endblock %}

templates/admintemplates/adminbannerlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}


{% block title %}
Emenu-Admin BannerPage
{% endblock %}



{% block content %}

<div class="row">
	<div class="col-md-10">
		
        
	</div>
	<div class="col-md-2">
		<a href="{% url 'menuapp:adminbannercreate' %}"  style="font-size: 40px"><span class="fas fa-plus-circle text-primary"></span></a>
	</div>
</div>

    <h4>All Banners</h4>

    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th scope="col">S.N</th>
                <th scope="col">Title</th>
                <th scope="col">Caption</th>
                <th scope="col">Link</th>
                <th scope="col">Update</th>
            </tr>
        </thead>
        <tbody>
        	{% for slider in allsliders %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{slider.title}}</td>
                <td>{{slider.caption}}</td>
                <td>{{slider.link}}</td>
                <td>
                	<a href="{% url 'menuapp:adminbannerupdate' slider.id %} "><button class="btn btn-info">Edit</button></a>
                	<a href="{% url 'menuapp:adminbannerdelete' slider.id %}"><button class="btn btn-danger">Delete</button></a>
                </td>
                <td>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>




{% endblock %}

templates/admintemplates/admingallery.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}


{% block title %}
Emenu-Admin Gallery page
{% endblock %}

{% block content %}
  
  
{% endblock %}

templates/admintemplates/adminhome.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}


{% block title %}
Emenu-Admin HomePage
{% endblock %}



{% block content %}
{% for org in restro %}
<div class="row">
	<div class="col-md-6">
		<h3>Name of Organization: {{org.name}}</h3>
		<img src="{{org.logo.url}}" width="250">
		<h4>Email: {{org.email}}</h4>
		<h4>Phone: {{org.phone}}</h4>
		<h4>Mobile: {{org.mobile}}</h4>
		<h4>Address: {{org.address}}</h4>
	</div>
	<div class="col-md-6">
		<h3>About Us:</h3><br><h4>{{org.about}}</h4>
		<img src="{{org.profile_image.url}}" width="250">
		<a href=""><button class="btn btn-info">Update</button></a>
	</div>
	<br>
</div>
{% endfor %}
{% endblock %}

templates/admintemplates/adminitemdelete.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Item Delete Page
{% endblock %}



{% block content %}

<h3>Item Delete</h3>
<form method="POST">
	{% csrf_token %}
	<p>Are you sure you want to delete === " {{object.title}} " item ????</p>
	<button class="btn btn-danger">Yes</button>
	<a href="{% url 'menuapp:adminitemlist' %}" class="btn btn-primary">No</a>

</form>


{% endblock %}

templates/admintemplates/adminmenucreate.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}


{% block title %}
Emenu-Admin MenuCreate Page
{% endblock %}



{% block content %}

<h3> Menu Form</h3>

<form action="." method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" name="Submit">	
</form>



{% endblock %}

templates/admintemplates/adminmenudelete.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Menu Delete Page
{% endblock %}



{% block content %}

<h3>Menu Delete</h3>
<form method="POST">
	{% csrf_token %}
	<p>Are you sure you want to delete === " {{object.title}} " Menu ????</p>
	<button class="btn btn-danger">Yes</button>
	<a href="{% url 'menuapp:adminmenulist' %}" class="btn btn-primary">No</a>

</form>


{% endblock %}

templates/admintemplates/adminmenudetail.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}


{% block title %}
Admin Menu Detail Page
{% endblock %}


{% block content %}


	<h3>
		 Items Under {{ menuobject }} menu
	</h3>

	<table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th scope="col">S.N</th>
                <th scope="col">Name of Item</th>
                <th scope="col">Image</th>
                <th scope="col">Price(Rs.)</th>
                <th scope="col">Update</th>
            </tr>
        </thead>
        <tbody>
        	{% for items in menuobject.item_set.all %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{items.name}}</td>
                <td><img src="{{items.photo.url}}" width="70"></td>
                <td>{{items.price}}</td>
                <td>
                    <a href="{% url 'menuapp:adminitemupdate' items.id %} "><button class="btn btn-info">Edit</button></a>
                    <a href="{% url 'menuapp:adminitemdelete' items.id %}"><button class="btn btn-danger">Delete</button></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/admintemplates/adminsignin.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}
		E-Menu Admin Signin
		{% endblock %}
	</title>
</head>
<body>
	<form action="." method="post">
		{% csrf_token %}
		{{form.as_p}}
		<div class="forgot-grid">
			<label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>Remember me</label>
			<div class="forgot">
				<a href="#">forgot password?</a>
			</div>
			<div class="clearfix"> </div>
		</div>
		<input type="submit" name="Sign In" value="Sign In">
		<div class="registration">
			Don't have an account ?
			<a class="" href="signup.html">
				Create an account
			</a>
		</div>
	</form>

</body>
</html>

templates/admintemplates/adminsignup.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}
		E-Menu Admin SignUp
		{% endblock %}
	</title>
</head>
<body>
		<form method="POST">
			{% csrf_token %}
			<div class="sign-u">
			{{form.username}}
			<div class="clearfix"> </div>
			</div>
			<div class="sign-u">
			{{form.email}}
			<div class="clearfix"> </div>
			</div>
			<h6>Login Information :</h6>
			<div class="sign-u">
			{{form.password}}
			<div class="clearfix"> </div>
			</div>
			<div class="sign-u">
			{{form.confirm_password}}
			</div>
			<div class="clearfix"> </div>
			<div class="sub_home">
			<input type="submit" value="Sign Up">
			<div class="clearfix"> </div>
			</div>
			<div class="registration">
			Already Registered.
			<a class="" href="{% url 'menuapp:adminsignin' %}">
			Login
			</a>
			</div>
		</form>

</body>
</html>

templates/admintemplates/adminstaffcreate.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}


{% block title %}
Emenu-Admin Staff Create Page
{% endblock %}



{% block content %}

<h3> Staff Form</h3>

<form action="." method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" name="Submit">	
</form>



{% endblock %}

templates/admintemplates/adminstaffdelete.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Staff Delete Page
{% endblock %}



{% block content %}

<h3>Staff Delete</h3>
<form method="POST">
	{% csrf_token %}
	<p>Are you sure you want to delete === " {{object.title}} " Staff ????</p>
	<button class="btn btn-danger">Yes</button>
	<a href="{% url 'menuapp:adminitemlist' %}" class="btn btn-primary">No</a>

</form>


{% endblock %}

templates/admintemplates/adminstafflist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}


{% block title %}
Emenu-Admin Stafflist Page
{% endblock %}



{% block content %}

<div class="row">
	<div class="col-md-10">
		
        
	</div>
	<div class="col-md-2">
		<a href="{% url 'menuapp:adminstaffcreate' %}"  style="font-size: 40px"><span class="fas fa-plus-circle text-primary"></span></a>
	</div>
</div>

    <h4>All Staffs</h4>

    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th scope="col">S.N</th>
                <th scope="col">Name of Staff</th>
                <th scope="col">Image</th>
                <th scope="col">Position</th>
                <th scope="col">Experience(Years)</th>
                <th scope="col">Update</th>
            </tr>
        </thead>
        <tbody>
        	{% for staffs in staffobjects %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{staffs.name}}</td>
                <td><img src="{{staffs.photo.url}}" width="70"></td>
                <td>{{staffs.position}}</td>
                <td>{{staffs.experience}}</td>
                <td>
                	<a href="{% url 'menuapp:adminstaffupdate' staffs.id %} "><button class="btn btn-info">Edit</button></a>
                	<a href="{% url 'menuapp:adminstaffdelete' staffs.id %}"><button class="btn btn-danger">Delete</button></a>
                </td>
                <td>
                </td>
            </tr>
            {% endfor %}
            {% if page_obj.has_other_pages %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                {% endif %}
                {% for n in page_obj.paginator.page_range %}
                    {% if page_obj.number == n %}
                        <li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ n }}">{{n}}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number}}">Next</a></li>
                {% else %}
                  <li class="page-item disabled"><span class="page-link">Next</span></li>
                {% endif %}
            </ul>
            {% endif %}
        </tbody>
    </table>




{% endblock %}